# Generated by Django 5.2.13 on 2026-04-20 10:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_api_key_alter_tenant_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.CharField(default=core.models.generate_api_key, editable=False, max_length=64, unique=True),
        ),
    ]
