# Generated by Django 5.2.13 on 2026-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
