# Generated by Django 5.2.13 on 2026-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('length_km', models.FloatField()),
                ('diameter_inches', models.FloatField()),
                ('volume_capacity', models.FloatField(help_text='Line fill capacity')),
                ('status', models.CharField(choices=[('FLOWING', 'Flowing'), ('STATIC', 'Static'), ('OFFLINE', 'Offline'), ('PIGGING', 'Pigging'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('current_flow_rate', models.FloatField(default=0.0)),
                ('current_pressure', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geojson_path', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_code', models.CharField(default='#cccccc', max_length=20)),
                ('specific_gravity', models.FloatField(blank=True, null=True)),
                ('max_interface_mixing_tolerance', models.FloatField(default=0.0, help_text='Acceptable mixture volume in bbls/liters')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_capacity', models.FloatField(help_text='Maximum roof capacity')),
                ('safe_fill_capacity', models.FloatField(help_text='Operational safe fill limit')),
                ('current_volume', models.FloatField(default=0.0)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
