# Generated by Django 5.2.13 on 2026-04-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='pipelinesegment',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_terminating', to='assets.depot'),
        ),
        migrations.AddField(
            model_name='pipelinesegment',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments_originating', to='assets.depot'),
        ),
        migrations.AddField(
            model_name='pipelinesegment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_segments', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='tank',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='assets.depot'),
        ),
        migrations.AddField(
            model_name='tank',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='assets.producttype'),
        ),
        migrations.AlterUniqueTogether(
            name='producttype',
            unique_together={('tenant', 'name')},
        ),
    ]
