# Generated by Django 5.2.13 on 2026-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('entity_type', models.CharField(choices=[('TANK', 'Tank'), ('PIPELINE', 'Pipeline Segment'), ('BATCH', 'Batch'), ('VESSEL', 'Vessel')], max_length=20)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of the specific Tank, Pipeline, etc.', null=True)),
                ('metric', models.CharField(help_text='e.g., ullage, pressure, status, interface_volume', max_length=50)),
                ('condition', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('==', 'Equals'), ('!=', 'Not Equals')], max_length=5)),
                ('threshold', models.FloatField()),
                ('message_template', models.CharField(help_text='Use {entity} and {value} in string', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
