# Generated by Django 5.2.13 on 2026-04-20 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flow_rate', models.FloatField(help_text='Current flow rate in BPH')),
                ('daily_volume', models.FloatField(default=0.0, help_text='Total volume passed since last 24h')),
                ('capacity_utilization', models.FloatField(help_text='Percentage of design capacity used')),
                ('operating_pressure', models.FloatField(blank=True, null=True)),
                ('operating_temperature', models.FloatField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='assets.pipelinesegment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
