# Generated by Django 5.2.13 on 2026-04-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_identifier', models.CharField(max_length=100, unique=True)),
                ('total_volume', models.FloatField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('current_position_km', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('destination_depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destined_batches', to='assets.depot')),
                ('origin_depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_batches', to='assets.depot')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.producttype')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_batches', to='assets.pipelinesegment')),
            ],
        ),
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('position_km', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('interface_mixing_volume', models.FloatField(default=0.0, help_text='Estimated mixture with adjacent batch')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operations.batch')),
            ],
        ),
        migrations.CreateModel(
            name='VesselDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=200)),
                ('total_volume', models.FloatField()),
                ('discharged_volume', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BERTHED', 'Berthed'), ('DISCHARGING', 'Discharging'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.producttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('terminal_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_discharges', to='assets.depot')),
            ],
        ),
    ]
