# Generated by Django 5.2.13 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchhistory',
            name='accumulated_volume',
            field=models.FloatField(default=0.0, help_text='Total volume passed since batch start'),
        ),
        migrations.AddField(
            model_name='batchhistory',
            name='flow_rate',
            field=models.FloatField(blank=True, help_text='Flow rate in barrels per hour', null=True),
        ),
    ]
